env:
  browser: true
  es2021: true
  node: true
extends:
  - 'airbnb-base'
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
